---

- name: install dns srv
  hosts: dns
  remote_user: user
  become: true

  roles:
  - dns

- name: install dhcp srv
  hosts: dhcp
  remote_user: user
  become: true

  roles:
  - dhcp

- name: install ldap srv
  hosts: ldap
  remote_user: user
  become: true

  roles:
  - ldap

- name: install mail srv
  hosts: mail
  remote_user: user
  become: true

  roles:
  - mail

- name: install web srv
  hosts: web
  remote_user: user
  become: true

  roles:
  - web
  - nextcloud