---

- name: Modification /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^'
    line: "10.0.0.2  srv-dns01.domain.lan  srv-dns01"
    state: present

- name: Copy hostname Conf File
  template:
    src:  hostname
    dest: /etc/hostname

- name: Copy hostname Conf File
  template:
    src:  resolv.conf
    dest: /etc/resolv.conf

- name: Change DNS Address to 10.0.0.2
  replace:
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3
    regexp: 'DNS1=8.8.8.8'
    replace: 'DNS1=10.0.0.2'
  notify:
      - Restart Network

- name: Install OpenLDAP
  yum:
    pkg: ['openldap','compat-openldap','openldap-clients','openldap-servers','openldap-servers-sql', 'openldap-devel']
    state: latest
  notify:
      - Start slapd

- name: Copy db.ldif File
  template:
    src:  db.ldif
    dest: db.ldif

- name: Apply db.ldif
  shell: /usr/bin/ldapmodify -Y EXTERNAL  -H ldapi:/// -f db.ldif

- name: Copy monitor.ldif File
  template:
    src:  monitor.ldif
    dest: monitor.ldif

- name: Apply monitor.ldif
  shell: /usr/bin/ldapmodify -Y EXTERNAL  -H ldapi:/// -f monitor.ldif

- name: cp
  command: echo "cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG"

- name: chown
  command: echo "chown ldap:ldap /var/lib/ldap"

- name: Add LDAP schema (cosine.ldif)
  shell: /usr/bin/ldapadd -Y EXTERNAL  -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
  ignore_errors: true

- name: Add LDAP schema (inetorgperson.ldif)
  shell: /usr/bin/ldapadd -Y EXTERNAL  -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif
  ignore_errors: true

- name: Add LDAP schema (nis.ldif)
  shell: /usr/bin/ldapadd -Y EXTERNAL  -H ldapi:/// -f /etc/openldap/schema/nis.ldif
  ignore_errors: true

- name: Copy base.ldif File
  template:
    src:  base.ldif
    dest: base.ldif

- name: Apply base.ldif
  shell: /usr/bin/ldapadd -x -w "{{ ROOT_PW }}" -D "{{ ROOT_DN }}" -f base.ldif
  ignore_errors: true
  
- name: Copy testuser.ldif File
  template:
    src:  testuser.ldif
    dest: testuser.ldif

- name: Apply testuser.ldif
  shell: /usr/bin/ldapadd -x -w "{{ ROOT_PW }}" -D "{{ ROOT_DN }}" -f testuser.ldif
  ignore_errors: true

- name: Open firewall port
  firewalld:
    service: ldap
    permanent: true
    state: enabled
    immediate: yes