---

- name: Modification /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^'
    line: "10.0.0.2  srv-dns01.domain.lan  srv-dns01"
    state: present

- name: Copy hostname Conf File
  template:
    src:  hostname
    dest: /etc/hostname

- name: Copy hostname Conf File
  template:
    src:  resolv.conf
    dest: /etc/resolv.conf

- name: Change DNS Address to 10.0.0.2
  replace:
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3
    regexp: 'DNS1=8.8.8.8'
    replace: 'DNS1=10.0.0.2'
  notify:
  - Restart network

- name: install epel
  yum:
      name: ['epel-release']
      state: present
      update_cache: yes

- name: install borgbackup
  yum:
      name: ['borgbackup']
      state: present
      update_cache: yes
