---

- name: Open Port DNS
  firewalld:
    service: dns
    permanent: true
    state: enabled

- name: Modification /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^'
    line: "10.0.0.2  srv-dns01.domain.lan  srv-dns01"
    state: present

- name: Ajout du Hostname
  replace:
    dest: /etc/hostname
    regexp: 'localhost.localdomain'
    replace: 'srv-dns01.domain.lan'

- name: Restart Network
  service: 
    name: network 
    state: restarted

- name: Install Bind & Bind Utils
  yum:
    pkg: ['bind','bind-utils']
    state: latest

- name: Change DNS Address to 10.0.0.2
  replace:
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3
    regexp: 'DNS1=8.8.8.8'
    replace: 'DNS1=10.0.0.2'

- name: Restart Network
  service: 
    name: network 
    state: restarted

- name: Copy Named Conf File
  template:
    src:  named.conf
    dest: /etc/named.conf

- name: Copy Zone File
  template:
    src:  named.rfc1912.zones
    dest: /etc/named.rfc1912.zones

- name: Copy Forward Zone File
  template:
    src:  db.domain.lan
    dest: /var/named/db.domain.lan

- name: Copy Reverse Zone File
  template:
    src:  db.0.0.10.in-addr.arpa
    dest: /var/named/db.0.0.10.in-addr.arpa

- name: Copy ddns.key File
  template:
    src:  ddns.key
    dest: /etc/named/ddns.key

- name: Restart DNS
  service: 
    name: named
    state: restarted